apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: quickstarts-inat
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: quickstarts-inat
    app.kubernetes.io/part-of: quickstarts-3
  name: quickstarts-inat
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app.kubernetes.io/instance: quickstarts-inat
status:
  loadBalancer: {}
